### PR TITLE
add check for mpt2sas RAID adapaters

### PR DESCRIPTION
**Pull request by mhagdorn**
check mpt2sas hardware controllers, eg Dell PERC H200 using the sas2ircu utility.

### CODE REVIEW

**Comment by analytically** [comment]
Hi, great addition. Can you please update your code to comply to our coding guidelines? See https://travis-ci.org/sensu-plugins/sensu-plugins-raid-checks/jobs/79875825 - thanks!

**Comment by mhagdorn** [comment]
the weekend got in the way - fixed the style issues

**Comment by analytically** [comment]
Thanks for that, one last thing, would you mind updating the description to be more specific? What SAS controllers, etc.

**Comment by mhagdorn** [comment]
updated the documentation

**Pull request merged**
