### PR TITLE
Add Ruby 2.4.1 testing

### PR DESCRIPTION
**Pull request by thomasriley**
## Pull Request Checklist

sensu-plugins/sensu-plugins-feature-requests#27

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [x] RuboCop passes

- [x] Existing tests pass 

#### Purpose
- Add Ruby 2.4.1 testing

### CODE REVIEW

**Comment by thomasriley** [comment]
This one is failing on something that does not look immediately obvious to me. I will take a look shortly.

**Comment by majormoses** [comment]
It looks like we need to `require 'timeout'` I will pull it locally and see if I can figure out where its needed to get this working.

**Comment by majormoses** [comment]
OK I figured it, it appears to be an issue with the stub for `timeout` and `timeout-extensions` which after commenting this out it seemed to fixed the problem, I also noted that I don't see anywhere in our code that calls timeout and I validated that I dont see that in a least a few plugins I checked. lets try removing that and see if that works for you.

**Comment by majormoses** [comment]
@thomasriley awesome just need an entry in the changelog to reflect the latest change. If it actually does break something it is helpful to look through changelog and see a quick indicator.

I would put it under a `### Removed` header. Its not a known breaking change but there is always some risk with removing stuff.

**Comment by thomasriley** [comment]
@majormoses of course, will add that now :)

Seems like it's not the first time the timeout stub has been giving grief within a sensu plugin:

https://github.com/sensu-plugins/sensu-plugins-ponymailer/issues/3#issuecomment-160853934

**Comment by thomasriley** [comment]
@majormoses thanks for the help figuring that one out :)

**Comment by majormoses** [comment]
@thomasriley no problem at all I had to spend a little time reading through some ruby docs and yes I did read through that issue after I had it working locally and was checking if we had seen this in other gems.

**Review by majormoses — APPROVED** [review]
LGTM

**Pull request merged**
